debug: false

server:
  port: 8081

#Log

spring:
#  profiles:
#   active: develop
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
  redis:
    host: 10.19.19.54
    port: 19000
    password: codis123456
    pool:
      max-active: 100
      max-idle: 5
      max-wait: 60000


