debug: false

server:
  port: 8080

spring:
#  profiles:
#   active: develop
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
  redis:
    port: 6379
    host: 127.0.0.1
    pool:
      max-active: 100
      max-idle: 5
      max-wait: 60000

